### ISSUE TITLE
Inventory delation

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#10]
#### Introduction

When you click on resurrect very fast, you are teleported to the spawn point.

But sometimes, you click really fast and you stuck in place in the HG battle area instead of being teleported to the spawn point, you're teleported after some seconds...
This situation is embarrassing because the time you resurrect on the arena, you grab some of your stuff !

Conclusion, you're teleported to the spawn with some of your precedent items...
#### Solution

Add a routine wich delete the inventory after a resurrected player, maybe a "for" loop, that erase the inventory every 1sec for 5 second in total.

**Comment by Lymkwi** [comment]
I know a mod that deletes player's inventories when they die, it's easy to do. I will code it and push it later.

**Comment by BetterToAutomateTheWorld** [comment]
We don't need to erase the player inventory when they die... Dropondie mod needs to do its job and drop the item of the dead player.

BUT, the dead player must NOT catch his items because of a usebug/lag of the resurection feature.

Erase the player 1/2/3/4/5sec after his resurrection is maybe a solution...

**Comment by Lymkwi** [comment]
`minetest.register_on_respawnplayer` is the function I will be using, it will erease a player's inventory after they respawned, so that dropondie will have time to do its stuff before we delete the full inventory to be sure the player is not carrying items they get after dying.
I will take advantage of being away for a few days to work offline on a few little tasks like these. I should push my modifications in the evening.

**Comment by ghost** [comment]
oop's fixed https://github.com/MinetestForFun/hungry_games/commit/d7576d6af1bf6fbd385cd03d29f74e1e88eaa506 and https://github.com/MinetestForFun/hungry_games/commit/351262bbc4073275b5c0c335df964e033b63d1c1

**Comment by BetterToAutomateTheWorld** [comment]
Great ! thank your for this very interresting commits/fixs :)
