### ISSUE TITLE
Is this a hacked client?

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-hungry_games#100]
This was in the pre-fight lobby area before a match. He was shooting arrows all over the lobby. Then he decided to drop some of his items, including a bow and sword, on the ground which i couldn't pick up. In this screenshot you can see he is wearing armor:  
![pregame](https://cloud.githubusercontent.com/assets/15715378/17121346/0fd1f1a6-52a1-11e6-9a23-a7680791280d.png)

Then once we get in the game, i'm fighting him until he dies and he never has a health bar above him:
![healthbar](https://cloud.githubusercontent.com/assets/15715378/17121364/270a61f0-52a1-11e6-8402-28ec28631c22.png)

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Armor in the lobby :
Sometimes, it happens, maybe a lag issue because, normally, the inventory/stuff is reseted when the arena is done and the player teleported to the lobby.
I didn't remember if the inventory is reseted when the player is teleported from the lobby to the arena, we need to check it, if the inventory/stuff/craft grid is reseted, no need to be afraid.

Health bar gone :
It's a bug with the "hud_bar" mod, we already see it but didn't fix it, maybe we need to add a loop that re-add the bar every x secs/mins or fix the source of the bug

**Comment by aerozoic** [comment]
I took those pics only a few minutes apart, and it's the same player in both pics. I also played more than one game with this player and he never had a health bar. That's one hell of a coincidence.

:large_orange_diamond:

**Comment by Lymkwi** [comment]
@Cyberpangolin I haven't heard about the hud_bar bug related to gauges. You can't kill gauges.
All of this makes me think indeed that this is a hacked client. I've done this myself on Classic. If you prevent the client from sending real damage packets, the server will just ignore all damages. It is also possible that this player somehow glitched and respawned with health at 0 or under, and became invincible (which I doubt is possible).
I suggest @Darcidride takes a look at their player file.

**Comment by BetterToAutomateTheWorld** [comment]
For a more accurate thread, thanks to continue here : https://github.com/MinetestForFun/server-minetestforfun-hungry_games/issues/102
