### ISSUE TITLE
Improved sprint mod

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#21]
Take care of these modifications, our sprint mod have some features with the click when sprinting which stops the sprint, we don't need it for HG.

**Comment by Lymkwi** [comment]
Do you mean that you want us to reprogram the click-to-stop-sprinting feature?

**Comment by BetterToAutomateTheWorld** [comment]
Read the issue carefully please, I said **"we don't need it for HG"**
(Come to IRC if you want to ask us or confirm something :))

So, we need the MFF sprint mod, **without** the click-to-stop-sprinting feature.

**Comment by Lymkwi** [comment]
Oh, ok. I didn't understand why you talked about this issue, because we already copied the full `esprint.lua` file from MFF to HG, removed a few mana/maxStamina stuff we don't need, and it was done.
I can not come on IRC, my connection is terribly slow and I have to use a smartphone acting as a router to access the internet (which I cannot do more than 30 minutes per day).
Anyway, the mouse click issue should be gone.

**Comment by ObaniGemini** [comment]
That's why you're not as active as usual @LeMagnesium :)

**Comment by BetterToAutomateTheWorld** [comment]
This issue is useless, the mod was already merged.
Thank you @LeMagnesium !
