### ISSUE TITLE
Some bugs after the merge

### ISSUE THREAD

**Issue by Ataron** [MinetestForFun/server-minetestforfun-hungry_games#47]
After the merge there are some bugs : 
- [x] We don't lost our armors after the end of a game . => https://github.com/MinetestForFun/hungry_games/commit/ebbf19721ae51b7d44c8e16c9a29405f845c0e05
- [x] A unknow node spawned into chests. (maybe mithril armor i didn't see any in 10 games)
- [x] If the unknow isn't the mithril armors, there are no more.

**Comment by ghost** [comment]
mithril armors is enable only if there is moreores mod.

> if not minetest.get_modpath("moreores") then
>     ARMOR_MATERIALS.mithril = nil

this commit has erased all better textures :( https://github.com/MinetestForFun/hungry_games/commit/2c1e588e47b998571ad3e9707837edd8044d16eb

**Comment by BetterToAutomateTheWorld** [comment]
@LeMagnesium => many mistakes in your 3d_armor mod update :
- For the armors wich isn't lost, that's not a very important problem BUT, we need to check why there aren't removed when players spawn into the lobby
- The unknow is the mithril armor pieces...
  So need to comment the mod moreores needs to display/use in-game this armor because of we don't need the craft recipe, just the chests loots.
- For the textures, please revert your mistakes...
  You erase our textures in your commit... that's at least the 10th times you do it... PLEASE find an another way to merge mods ! (Don't merge everything without checked the textures)

@LeMagnesium, please, you should check in-game your code before pushed it to the repository

**Comment by Lymkwi** [comment]
@Ombridride : How should I know that a texture is from us? How should I know you prefer it upon the one from the original repository? I will remove all my modifications regarding textures and let **you** merge them. I have absolutly no opinion about them and I can't choose between two of them.
Otherwise, I'm fixing everything.

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/hungry_games/commit/ebbf19721ae51b7d44c8e16c9a29405f845c0e05
