### ISSUE TITLE
player skins?

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun-hungry_games#49]
It could be a good feature to add skins to the players, for an easier war of recognition. And for fun. i mean, do I really have to put arguments here? :D

**Comment by ObaniGemini** [comment]
I don't understand at all what you mean

**Comment by Ataron** [comment]
He wants skins to recognize who is who.

**Comment by Lymkwi** [comment]
~~Just agree to choose an unique skin. We already have `u_skins`. We don't need `player_textures`, nor any other skin mod, nor a reservation system. Pick an unique one and stick to it.~~
Ok, wrong server.
Why not. Player textures or simple_skins should work.

**Comment by Lymkwi** [comment]
After a discussion we had with @Ombridride, we agreed to create a mod that would not exactly do what you wanted. It would give a specific skin to players using that system :
- The first 3 players (according to ranks) would have a fancy skin with a cap
- The players ranked 4th to 10th would have a second skin, different from the default one
- The other players would have the default skin

We chosen this system because it follows the KISS standard. It kept the subgame simple, light & stupid; and it's automatic.

**Comment by BetterToAutomateTheWorld** [comment]
#### Skins chosen

1 to 3 : Link
![link_skin](https://lut.im/5Qp5dhY3/yDTqJr0z)
4 to 10 : Altier (/ Altair)
![altair_skin](https://lut.im/qDrHq5sy/2t8InJVS)
11 and more : Defaut skin
![default_skin](https://raw.githubusercontent.com/MinetestForFun/hungry_games/605100e52cf34933dc8ab1524abd7477bba5cb25/mods/playermodel/models/character.png)

Need to code this now !

**Comment by Lymkwi** [comment]
Have you pushed the textures yet?

**Comment by BetterToAutomateTheWorld** [comment]
No, they still in the u_skins mod of MFF repository

Ask Ataron for the texture number/complet name if you want to extract them

**Comment by Ataron** [comment]
I gave him the numbers.

**Comment by BetterToAutomateTheWorld** [comment]
Done https://github.com/MinetestForFun/hungry_games/commit/7583ccf477c03c56458eeaf881b849cbbe41489b

I closed the issue.
