### ISSUE TITLE
Add a value to the ranked board

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#53]
We need to displayed the "ratio" for information purpose on the ranked board.

Because this information is more useful for define the level of the ranked players

The ratio is calculated with : **maxnumber_play_game divided** by **number_win_game**

**Comment by Lymkwi** [comment]
"maxnumber_play_game" does not mean anything. I personally think that what you meant is either :
- `nb_wins`/`nb_games`
- or `nb_wins`/`global_amount_of_games_ever_player`

So far I've commited the first option. I'm gonna have to implement a global counter if you want the second option.

@crabman77 decided to use a percentage instead of a ratio. Appart from that, everything was correctly commited.

**Comment by ghost** [comment]
Fixed https://github.com/MinetestForFun/hungry_games/commit/fc7859581f6d9c182cbe607c03257dcff283c420
and fixed better info name https://github.com/MinetestForFun/hungry_games/commit/c94cfdc926a2b45b91a05aeb7bdde59a61acc02e
