### ISSUE TITLE
Apple

### ISSUE THREAD

**Issue by Ataron** [MinetestForFun/server-minetestforfun-hungry_games#54]
We can put apples on the map and destroy sources like lava or water with that.
@paly2 destroyed one like that accidentally.

**Comment by Lymkwi** [comment]
We should remove apples generated in trees, and make those already generated unbreakable.
EDIT: Err, no. Maybe you should just remove the apples from the lobby. (forget about the game area, it's not that important, or if you mind that too, remove all apples.)

**Comment by Ataron** [comment]
It's ingame that @paly2 broke a lava source.

**Comment by ObaniGemini** [comment]
And players have also fun by destroying water sources in races ..........

**Comment by Lymkwi** [comment]
We have to prevent players from placing apples. They just need to eat them.
EDIT: There is no possible way to avoid placing a node.. My idea would be to create an unplacable item, and a node. When digging the node, you would get the unplacable item.
Or even simpler, turn apples into items instead of nodes.

**Comment by Lymkwi** [comment]
https://github.com/LeMagnesium/hungry_games/commit/93aa18c40f9082efbdf3565448077ab7a9ede2a4
Needs reviews.

**Comment by ghost** [comment]
Fixed https://github.com/MinetestForFun/hungry_games/commit/dd6436209c4ac81504c93ddfebc1b23e82154835

**Comment by BetterToAutomateTheWorld** [comment]
Maybe also add vessels items type ?
(empty drink, water glass, etc)
