### ISSUE TITLE
Need to check/investigate it

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#91]
![](http://i.imgur.com/odaChdO.png)

**Comment by Lymkwi** [comment]
As far as I remember, when you chose to watch someone in the lobby before a game starts, you're considered as a skipper.
I'll check the code though, but that's the most logical way of getting skip to work with spectating.

**Comment by BetterToAutomateTheWorld** [comment]
I agree, but we maybe need to add a _random_messages_ + some signs around the "eyes"(spectator blocks) to explain that

**Comment by Lymkwi** [comment]
So, I ran tests. It seems that when you watch someone and enter a game, you follow that person, but you're not considered as a player, but if you had voted before, your vote apparently stays, and when the game starts, you're kicked from spectating, while playing in the game (you still have hunger and health bar showing up)
I'll fix that.

**Comment by Lymkwi** [comment]
I had to do a workaround... basically, watching someone else before going into a game will make you skip, but you'll stay as a skipper until you vote. Since hg's engine is closed in hungry_games/engines.lua, I have no control over the skip/vote/registrant variables.

https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/01359e08820c5de0f3b07241097a9efccf0add3e
